
import java.awt.HeadlessException;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Tomas
 */
public class Form extends javax.swing.JFrame {

    private Conversor convesorSelected = null;
    private List<Conversor> conversores = new ArrayList<>();
    private boolean convertirAValor2;

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        this.setTitle("Conversor");
        this.setLocationRelativeTo(null);
        conversores.add(new ConversorKilogramoLibra());
        conversores.add(new ConversorKilometroMilla());
        conversores.add(new ConversorCelsiusFahrenheit());
        for (Conversor conversor : conversores) {
            cbConversores.addItem(conversor.getName());
        }

        changeComboBox();
    }

    private void changeComboBox() {
        int selectedIndex = cbConversores.getSelectedIndex();
        convesorSelected = conversores.get(selectedIndex);
        this.lblUnidad1.setText(convesorSelected.getLabel1());
        this.lblUnidad2.setText(convesorSelected.getLabel2());
    }

    private void convertirAValor2() {
        String valorString = txtUnidad1.getText().replace(',', '.');
        Double valorDouble = getValueDouble(valorString);
        Double valor2 = convesorSelected.convertValue1(valorDouble);
        txtUnidad2.setText(String.format("%.2f", valor2));
    }

    private void convertirAValor1() {
        String valorString = txtUnidad2.getText().replace(',', '.');
        Double valorDouble = getValueDouble(valorString);
        Double resultado = convesorSelected.convertValue2(valorDouble);
        txtUnidad1.setText(String.format("%.2f", resultado));
    }

    private Double getValueDouble(String valor) {
        Double valorDouble = 0.0;
        try {
            final String toLowerCase = valor.toLowerCase();
            if (toLowerCase.endsWith("f") || toLowerCase.endsWith("d")) {
                throw new NumberFormatException("La unidad tiene una 'f' o una 'd'");
            }
            valorDouble = Double.valueOf(valor);
        } catch (NumberFormatException ex) {
            System.out.println("Error al convertir ==> " + ex.getMessage());
            JOptionPane.showMessageDialog(this, "Error al convertir", "Error al convertir", JOptionPane.ERROR_MESSAGE);
        }
        return valorDouble;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbConversores = new javax.swing.JComboBox<>();
        txtUnidad1 = new javax.swing.JTextField();
        txtUnidad2 = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblUnidad1 = new javax.swing.JLabel();
        lblUnidad2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbConversores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConversoresActionPerformed(evt);
            }
        });

        txtUnidad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnidad1FocusLost(evt);
            }
        });
        txtUnidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidad1ActionPerformed(evt);
            }
        });

        txtUnidad2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUnidad2FocusLost(evt);
            }
        });

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        jLabel1.setText("Conversor");

        lblUnidad1.setText("jLabel2");

        lblUnidad2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(233, 233, 233)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbConversores, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblUnidad1)
                                        .addComponent(lblUnidad2))
                                    .addGap(103, 103, 103)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUnidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUnidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbConversores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidad1))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConvertir)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUnidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUnidad2)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbConversoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConversoresActionPerformed
        changeComboBox();
    }//GEN-LAST:event_cbConversoresActionPerformed

    private void txtUnidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidad1ActionPerformed

    private void txtUnidad1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnidad1FocusLost
        convertirAValor2 = true;
    }//GEN-LAST:event_txtUnidad1FocusLost

    private void txtUnidad2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUnidad2FocusLost
        convertirAValor2 = false;
    }//GEN-LAST:event_txtUnidad2FocusLost

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        if (convertirAValor2) {
            convertirAValor2();
        } else {
            convertirAValor1();
        }
    }//GEN-LAST:event_btnConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Form().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox<String> cbConversores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUnidad1;
    private javax.swing.JLabel lblUnidad2;
    private javax.swing.JTextField txtUnidad1;
    private javax.swing.JTextField txtUnidad2;
    // End of variables declaration//GEN-END:variables
}
